# Generated by Django 3.0.4 on 2020-04-09 15:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True)),
                ('dt_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('_total_servicehours', models.DecimalField(decimal_places=1, default=Decimal('0'), editable=False, max_digits=12)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('website', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-_total_servicehours'],
            },
        ),
    ]
