# Generated by Django 3.0.5 on 2020-04-11 11:37

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import students.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True)),
                ('dt_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('_total_servicehours', models.DecimalField(decimal_places=1, default=Decimal('0'), editable=False, max_digits=12)),
                ('username', models.CharField(help_text='Defaults to mcps_id.', max_length=50, unique=True)),
                ('mcps_id', models.PositiveIntegerField(unique=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('grade', models.PositiveSmallIntegerField(choices=[(6, 'Sixth'), (7, 'Seventh'), (8, 'Eighth'), (9, 'Ninth'), (10, 'Tenth'), (11, 'Eleventh'), (12, 'Twelth')], null=True)),
                ('phone', models.CharField(blank=True, max_length=14, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('first_period_teacher', models.CharField(blank=True, max_length=30, null=True)),
                ('parent_name', models.CharField(blank=True, max_length=30, null=True)),
                ('parent_phone', models.CharField(blank=True, max_length=14, null=True)),
                ('parent_phone_other', models.CharField(blank=True, max_length=14, null=True)),
                ('avatar', models.CharField(default=students.models.pick_random_avatar, max_length=50)),
                ('_beginning_total_servicehour_balance', models.DecimalField(decimal_places=1, default=Decimal('0'), help_text='Beginning balance outside of SSLHours, to be credited only by admin.', max_digits=6)),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='schools.School')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='teams.Team')),
            ],
            options={
                'ordering': ['-_total_servicehours'],
            },
        ),
        migrations.CreateModel(
            name='Snapshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True)),
                ('position', models.PositiveSmallIntegerField()),
                ('out_of', models.PositiveSmallIntegerField()),
                ('leaderboard', models.CharField(choices=[('students', 'Students'), ('middle_schools', 'Middle Schools'), ('high_schools', 'High Schools'), ('teams', 'Teams'), ('activities', 'Activities'), ('organizations', 'Organizations')], max_length=14)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshots', to='students.Student')),
            ],
            options={
                'ordering': ['-dt_created'],
            },
        ),
    ]
