# Generated by Django 3.0.5 on 2020-04-11 11:37

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True)),
                ('dt_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('_total_servicehours', models.DecimalField(decimal_places=1, default=Decimal('0'), editable=False, max_digits=12)),
                ('mcps_school_id', models.PositiveSmallIntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('school_type', models.CharField(choices=[('middle', 'Middle'), ('high', 'High')], max_length=6)),
                ('address', models.CharField(max_length=100, unique=True)),
                ('city', models.CharField(max_length=40)),
                ('zip_code', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=14, unique=True)),
            ],
            options={
                'ordering': ['-_total_servicehours'],
            },
        ),
    ]
