# Generated by Django 3.0.5 on 2020-04-11 11:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='ssl_coordinators',
            field=models.ManyToManyField(blank=True, related_name='ssl_coordinated_schools', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='school',
            unique_together={('name', 'school_type')},
        ),
    ]
