# Generated by Django 3.0.4 on 2020-04-09 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('discussion', models.TextField()),
                ('_tally', models.SmallIntegerField(default=0)),
                ('status', models.CharField(default='open', max_length=10)),
                ('outcome', models.TextField()),
            ],
            options={
                'ordering': ['-_tally'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upordown', models.CharField(choices=[('up', 'up'), ('down', 'down')], max_length=4)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='votes', to='features.Feature')),
            ],
        ),
    ]
