# Generated by Django 3.0.5 on 2020-04-11 11:37

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt_created', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(help_text='Leave a comment for your SSL coordinator...')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceHour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('reflections', models.TextField(blank=True, null=True)),
                ('grade', models.PositiveSmallIntegerField(blank=True, choices=[(6, 'Sixth'), (7, 'Seventh'), (8, 'Eighth'), (9, 'Ninth'), (10, 'Tenth'), (11, 'Eleventh'), (12, 'Twelth')], null=True)),
                ('_status', models.CharField(default='incomplete', editable=False, max_length=10)),
                ('_total', models.DecimalField(decimal_places=1, default=Decimal('0'), editable=False, max_digits=4)),
                ('dt_created', models.DateTimeField(auto_now_add=True)),
                ('dt_updated', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicehours', to='activities.Activity')),
            ],
            options={
                'verbose_name': 'Service Hour',
                'verbose_name_plural': 'Service Hours',
                'ordering': ['-_total'],
            },
        ),
    ]
