# Generated by Django 3.0.5 on 2020-04-11 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        ('servicehours', '0001_initial'),
        ('schools', '0002_auto_20200411_0737'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servicehour',
            name='crediting_SSL_coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credited_servicehours', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicehour',
            name='school',
            field=models.ForeignKey(blank=True, help_text='School of student when this hour was credited.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicehours', to='schools.School'),
        ),
        migrations.AddField(
            model_name='servicehour',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicehours', to='students.Student'),
        ),
        migrations.AddField(
            model_name='servicehour',
            name='team',
            field=models.ForeignKey(blank=True, help_text='You can associate this time with a team or club. If you don\t see them here, email help@sslhours.com.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='servicehours', to='teams.Team'),
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='servicehour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='servicehours.ServiceHour'),
        ),
    ]
